version: '3.1'
services:
  api:
    build:
      context: ./
    image: nft/api:latest
    ports:
      - 9000:5000
    env_file:
      - ./api/.env
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: celo_user
      POSTGRES_PASSWORD: celo_pass
      POSTGRES_DB: celo-nft

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  redis:
    image: redis
    ports:
      - 6379:6379
