# Generated by Django 3.2.3 on 2021-05-18 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='token',
            new_name='wallet_token',
        ),
    ]
