# Generated by Django 3.2.4 on 2021-06-18 11:02

from django.db import migrations


def add_default_admin(apps, schema_editor):
    User = apps.get_model('users', 'User')
    User.objects.create_superuser("admin", None, "admin")


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210520_1058'),
    ]

    operations = [
        migrations.RunPython(add_default_admin, migrations.RunPython.noop),
    ]
