# Generated by Django 3.2.3 on 2021-05-20 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='file1',
            field=models.FileField(blank=True, default='', upload_to='items/file1/'),
        ),
        migrations.AddField(
            model_name='item',
            name='file2',
            field=models.FileField(blank=True, default='', upload_to='items/file2/'),
        ),
        migrations.AddField(
            model_name='item',
            name='on_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='royalties',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='token_amt',
            field=models.IntegerField(default=1),
        ),
    ]
