# Generated by Django 3.2.3 on 2021-05-20 11:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0004_item_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='like_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
