# Generated by Django 3.2.3 on 2021-05-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_auto_20210521_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cover_img',
            field=models.ImageField(blank=True, default='', upload_to='items/cover_images/'),
        ),
    ]
