# Generated by Django 3.2.3 on 2021-05-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_auto_20210527_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='creator_name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='item',
            name='owner_name',
            field=models.CharField(default='', max_length=128),
        ),
    ]
