# Generated by Django 3.2.3 on 2021-05-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_auto_20210527_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='creator_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='item',
            name='owner_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
