# Generated by Django 3.2.3 on 2021-05-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_auto_20210527_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='token_sold',
            field=models.IntegerField(default=0),
        ),
    ]
