# Generated by Django 3.2.3 on 2021-06-08 07:46
import uuid
from django.db import migrations


def add_default_contract_address(apps, schema_editor):
    Item = apps.get_model('items', 'Item')
    for item in Item.objects.all():
        item.contract_address = str(uuid.uuid4())
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0015_auto_20210608_0745'),
    ]

    operations = [
        migrations.RunPython(add_default_contract_address),
    ]
