# Generated by Django 3.2.4 on 2021-06-15 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0017_alter_item_contract_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('starting_bidding_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_bidding_price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='sell_type',
            field=models.IntegerField(choices=[(1, 'INSTANT_BUY'), (2, 'AUCTION')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='auction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.auction'),
        ),
    ]
