# Generated by Django 3.2.4 on 2021-06-17 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0019_auto_20210616_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sell_type',
            field=models.IntegerField(choices=[(1, 'INSTANT_BUY'), (2, 'AUCTION')], null=True),
        ),
    ]
