# Generated by Django 3.2.4 on 2021-06-18 10:57

from django.db import migrations


def add_default_categories(apps, schema_editor):
    Category = apps.get_model('items', 'Category')
    Category.objects.get_or_create(name="Hip Hop/Rap")
    Category.objects.get_or_create(name="Techno")
    Category.objects.get_or_create(name="R&B")
    Category.objects.get_or_create(name="Punk")
    Category.objects.get_or_create(name="Country")
    Category.objects.get_or_create(name="Indie Rock")
    Category.objects.get_or_create(name="Electro")
    Category.objects.get_or_create(name="Latin")
    Category.objects.get_or_create(name="Other")


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0020_alter_item_sell_type'),
    ]

    operations = [
        migrations.RunPython(add_default_categories),
    ]
