# Generated by Django 3.2.4 on 2021-06-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0021_auto_20210618_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='isFeatured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='isTopSeller',
            field=models.BooleanField(default=False),
        ),
    ]
