# Generated by Django 3.2.4 on 2021-06-21 10:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0021_auto_20210618_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='current_bidding_price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='auction',
        ),
        migrations.RemoveField(
            model_name='item',
            name='creator_name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='on_sale',
        ),
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sell_type',
        ),
        migrations.RemoveField(
            model_name='item',
            name='token_sold',
        ),
        migrations.RemoveField(
            model_name='token',
            name='owner_name',
        ),
        migrations.AddField(
            model_name='token',
            name='auction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.auction'),
        ),
        migrations.AddField(
            model_name='token',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='token',
            name='on_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='token',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='token',
            name='sell_type',
            field=models.IntegerField(choices=[(1, 'INSTANT_BUY'), (2, 'AUCTION')], default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('bid_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_set', to='items.auction')),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
