# Generated by Django 3.2.4 on 2021-06-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0022_auto_20210621_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='sell_type',
            field=models.IntegerField(choices=[(0, 'NONE'), (1, 'INSTANT_BUY'), (2, 'AUCTION')]),
        ),
    ]
