# Generated by Django 3.2.4 on 2021-06-23 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0023_auto_20210621_1304'),
        ('items', '0023_auto_20210622_0740'),
    ]

    operations = [
    ]
