# Generated by Django 3.2.4 on 2021-06-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0025_alter_item_contract_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='token_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
