# Generated by Django 3.2.4 on 2021-07-09 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0026_token_token_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='token',
            options={'ordering': ['collectible', 'owner', 'token_number']},
        ),
    ]
