# Generated by Django 3.2.4 on 2021-07-12 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0027_alter_token_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='token_id',
            new_name='item_id',
        ),
    ]
