# Generated by Django 3.2.4 on 2021-07-21 06:22

from django.db import migrations


def add_one_to_token_number(apps, schema_editor):
    Token = apps.get_model("items", "Token")
    token_list = []
    for token in Token.objects.all():
        token.token_number += 1
        token_list.append(token)

    Token.objects.bulk_update(token_list, ["token_number"], batch_size=1000)


def minus_one_to_token_number(apps, schema_editor):
    Token = apps.get_model("items", "Token")
    token_list = []
    for token in Token.objects.all():
        token.token_number -= 1
        token_list.append(token)

    Token.objects.bulk_update(token_list, ["token_number"], batch_size=1000)


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0031_auto_20210721_0622"),
    ]

    operations = [
        migrations.RunPython(add_one_to_token_number, reverse_code=minus_one_to_token_number),
    ]
