# Generated by Django 3.2.4 on 2021-07-21 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0032_auto_20210721_0622'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='token',
            options={'ordering': ['collectible', 'owner', 'on_sale', 'token_number']},
        ),
    ]
