# Generated by Django 3.2.4 on 2021-08-16 07:24

from django.db import migrations


def copy_file_two_to_item_file(apps, schema_editor):
    Item = apps.get_model("items", "Item")
    ItemFile = apps.get_model("items", "ItemFile")

    item_file_list = [
        ItemFile(
            item=item,
            file=item.file2,
        )
        for item in Item.objects.exclude(file2="").iterator()
    ]

    if item_file_list:
        ItemFile.objects.bulk_create(item_file_list, batch_size=1000)


def copy_item_file_to_file_two(apps, schema_editor):
    Item = apps.get_model("items", "Item")
    ItemFile = apps.get_model("items", "ItemFile")

    qs = ItemFile.objects.all().order_by("item").distinct("item")
    item_list = []
    for file in qs.iterator():
        item = file.item
        item.file2 = file.file
        item_list.append(item)

    if item_list:
        Item.objects.bulk_update(item_list, ["file2"], batch_size=1000)


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0034_itemfile"),
    ]

    operations = [
        migrations.RunPython(
            copy_file_two_to_item_file,
            reverse_code=copy_item_file_to_file_two,
        )
    ]
