# Generated by Django 3.2.4 on 2021-08-16 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0035_auto_20210816_0724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='file2',
        ),
    ]
