# Generated by Django 3.2.4 on 2021-08-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0036_remove_item_file2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='royalties',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
