# Generated by Django 3.2.4 on 2021-08-18 09:35
from decimal import Decimal

from django.db import migrations


def add_creator_as_collaborator(apps, schema_editor):
    Item = apps.get_model("items", "Item")
    ItemCollaborator = apps.get_model("items", "ItemCollaborator")
    collaborator_list = []

    item_qs = Item.objects.all()
    for item in item_qs.iterator():
        collaborator = ItemCollaborator(
            item=item,
            user=item.creator,
            wallet_token=item.creator.wallet_token,
            share_percentage=Decimal(100),
        )
        collaborator_list.append(collaborator)

    if collaborator_list:
        ItemCollaborator.objects.bulk_create(collaborator_list, batch_size=1000)


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0038_itemcollaborator"),
    ]

    operations = [
        migrations.RunPython(
            add_creator_as_collaborator,
        )
    ]
