# Generated by Django 3.2.4 on 2021-10-20 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0040_item_is_360_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='mint_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
